### ISSUE TITLE
missing elements in the rendered result in browser

### ISSUE THREAD

**Issue by aselvaraj** [raptorjs/raptor-renderer#3]
On the browser side, rendering components that produce partial nodes result in missing elements in the rendered results.

For example, a component that produces a column `<td>` for a table produce something like the following

`<td> foo <td>` => `foo`

**Comment by aselvaraj** [comment]
It's mainly due to rendering the result on the body element instead of the components parent element.

https://github.com/raptorjs/raptor-renderer/blob/master/lib/RenderResult-browser.js#L108

**Comment by mlrawlings** [comment]
Closed in https://github.com/raptorjs/raptor-renderer/commit/2c6d59d56ece1a053c17362417004a2632ff7e9e.  Published as `1.5.0`
